name = "MyPkg"
uuid = "b59f1ed4-4c8e-4fc7-a035-90d7cbd7aaf3"
authors = ["Kareem <88599145+KookiesNKareem@users.noreply.github.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
